version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./fastApiProjectPSI:/fastApiProjectPSI
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - DB_HOST=db
      - DB_NAME=mealsdb
      - DB_USER=postgres
      - DB_PASSWORD=pass
    depends_on:
      - db
    networks:
      - backend
    container_name: fastapi_app

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mealsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    container_name: postgres_db

networks:
  backend:

volumes:
  postgres_data:
